"""HW5 - Questionnaire data cleaning and analysis."""
import pathlib
from typing import Union, Tuple

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt


class QuestionnaireAnalysis:
    """
    Reads and analyzes data generated by the questionnaire experiment.
    Should be able to accept strings and pathlib.Path objects.
    """

    def __init__(self, data_fname: Union[pathlib.Path, str]):
        self.data_fname = pathlib.Path(data_fname)
        if not self.data_fname.exists():
            raise ValueError(f"File {self.data_fname} does not exist.")

    def read_data(self):
        """Reads the json data located in self.data_fname into memory, to
        the attribute self.data.
        """
        self.data = pd.read_json(self.data_fname)

    def show_age_distrib(self) -> Tuple[np.ndarray, np.ndarray]:
        bins = np.arange(0, 101, 10)
        ages = pd.to_numeric(self.data["age"], errors="coerce").dropna()
        hist, bins = np.histogram(ages, bins=bins)
        plt.hist(ages, bins=bins)
        plt.xlabel("Age")
        plt.ylabel("Count")
        plt.title("Age distribution")
        return hist, bins

    def remove_rows_without_mail(self) -> pd.DataFrame:
        def is_valid(email) -> bool:
            if not isinstance(email, str):
                return False
            if email.count("@") != 1:
                return False
            if email.startswith("@") or email.endswith("@"):
                return False
            if "." not in email:
                return False
            if email.startswith(".") or email.endswith("."):
                return False
            at_idx = email.index("@")
            if email[at_idx + 1] == ".":
                return False
            return True

        mask = self.data["email"].apply(is_valid)
        df = self.data[mask].reset_index(drop=True)
        return df

    def fill_na_with_mean(self) -> Tuple[pd.DataFrame, np.ndarray]:
        questions = ["q1", "q2", "q3", "q4", "q5"]
        df = self.data.copy()
        grades = df[questions].apply(pd.to_numeric, errors="coerce")

        rows_with_na = grades.isna().any(axis=1)
        arr = np.where(rows_with_na)[0]

        row_means = grades.mean(axis=1)
        filled = grades.apply(lambda col: col.fillna(row_means))
        df[questions] = filled
        return df, arr

    def score_subjects(self, maximal_nans_per_sub: int = 1) -> pd.DataFrame:
        questions = ["q1", "q2", "q3", "q4", "q5"]
        df = self.data.copy()
        grades = df[questions].apply(pd.to_numeric, errors="coerce")

        nan_counts = grades.isna().sum(axis=1)
        means = grades.mean(axis=1)
        scores = np.floor(means)
        scores[nan_counts > maximal_nans_per_sub] = np.nan

        df["score"] = pd.array(scores, dtype="UInt8")
        return df

    def correlate_gender_age(self) -> pd.DataFrame:
        questions = ["q1", "q2", "q3", "q4", "q5"]
        df = self.data.copy()
        df["age"] = pd.to_numeric(df["age"], errors="coerce")
        for q in questions:
            df[q] = pd.to_numeric(df[q], errors="coerce")
        df = df[df["age"].notna()]

        df = df.set_index([df.index, "gender", "age"])
        above_40 = df.index.get_level_values("age") > 40
        grouped = df.groupby(
            [df.index.get_level_values("gender"), above_40]
        )[questions].mean()
        grouped.index = grouped.index.set_names(["gender", "age"])
        return grouped